from typing import Protocol, Any

class VectorStorePort(Protocol):
    def upsert_chunks(self, chunks: list[dict[str, Any]]) -> None: ...
    def similarity_search(self, embedding: list[float], top_k: int, filters: dict[str, Any]) -> list[dict[str, Any]]: ...
    def index_stats(self) -> dict[str, Any]: ...
